export const CREDENTIALS = {
    CLIENT_ID: 'LVP1S4GT3IRDPLGCIKW20NHFLP0MH40SLX4ITXEJPBNGT54C',
    CLIENT_SECRET: 'WAJOH0CJHTIG4S0AQO3Z0L3WNIMQQFB4QNWLB3ENTCYFWAYO'
};

export const API_URL = 'https://api.foursquare.com/v2/venues/explore/';